Exploring The Dataset Collected, for our Epidemic Analysing and Monitoring System for Malaria and Diabetes

In [24]:
import pandas as pd

In [31]:
df = pd.read_csv('../artifacts/csv/health_data_eams_diabetes.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 926 entries, 0 to 925
Data columns (total 15 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Sr.No.                                 926 non-null    int64
 1   Address (Locality)                     921 non-null    object
 2   Age                                    926 non-null    object
 3   Sex                                    926 non-null    object
 4   Provisional Diagnosis                  926 non-null    object
 5   Type Of Test(s) Requested              183 non-null    object
 6   Test Result(s)                         0 non-null      float64
 7   Principal Diagnosis (New Case)         926 non-null    object
 8   Principal Diagnosis (Old Case)         3 non-null      object
 9   Principal Diagnosis (Recurring Case)   0 non-null      float64
 10  Additional Diagnosis (New Case)        403 non-null    object
 11  Additional Diagnosis (Old Case)        47 non-null     object
 12  Additional Diagnosis (Recurring Case)  1 non-null      object
 13  Pregnant Patient                       926 non-null    object
 14  NHIA Patient                           926 non-null    object
dtypes: float64(2), int64(1), object(12)
memory usage: 108.6+ KB

In [32]:
# remove columns that have little or no information
new_df = df.drop(columns=["Sr.No.", "Provisional Diagnosis", "Type Of Test(s) Requested", "Test Result(s)", "Principal Diagnosis (Old Case)", "Principal Diagnosis (Recurring Case)", "Additional Diagnosis (Old Case)", "Additional Diagnosis (Recurring Case)"])
new_df.head()
# new_df.info()
# new_df.isnull().sum()
# new_df.describe()
# new_df.describe(include=['O'])
# new_df.describe(include=['object'])

,Address (Locality),Age,Sex,Principal Diagnosis (New Case),Additional Diagnosis (New Case),Pregnant Patient,NHIA Patient
0,MADINA-NEW RD,67 Year(s),Female,E08.40 [Diabetes mellitus due to underlying co...,"R73.9 [Hyperglycaemia, unspecified]",No,Yes
1,"GBAWE , TELECOM",67 Year(s),Female,MEDI02A [Diabetes - Simple >=12 Yrs],NaN,No,Yes
2,MALLAM,52 Year(s),Female,E11.65 [Type 2 diabetes mellitus with hypergly...,NaN,No,No
3,awutu breku,44 Year(s),Female,E08.40 [Diabetes mellitus due to underlying co...,"L30.3 [Infective dermatitis] , N34.1 [Nonspeci...",No,Yes
4,BUBIASHIE-BEHIND ACADEMY,54 Year(s),Female,E11.40 [Type 2 diabetes mellitus with diabetic...,NaN,No,Yes

In [33]:
#flll NaN in additional diagnosis with the principal diagnosis
new_df.fillna({'Additional Diagnosis (New Case)': new_df['Principal Diagnosis (New Case)']}, inplace=True)
#convert age to integers
new_df['Age'] = new_df['Age'].str.replace(' Year(s)', '').astype(int)

In [41]:
# convert binary data to integers
new_df.fillna({'Sex': new_df['Sex'].mode()[0]}, inplace=True)
new_df['Sex'] = new_df['Sex'].str.lower().map({'male': 0, 'female': 1}).astype(int)
new_df['Pregnant Patient'] = new_df['Pregnant Patient'].map({'Yes': 1, 'No': 0}).astype(int)
new_df['NHIA Patient'] = new_df['NHIA Patient'].map({'Yes': 1, 'No': 0}).astype(int)

new_df.head()

,Address (Locality),Age,Sex,Principal Diagnosis (New Case),Additional Diagnosis (New Case),Pregnant Patient,NHIA Patient
0,MADINA-NEW RD,67,1,E08.40 [Diabetes mellitus due to underlying co...,"R73.9 [Hyperglycaemia, unspecified]",0,1
1,"GBAWE , TELECOM",67,1,MEDI02A [Diabetes - Simple >=12 Yrs],MEDI02A [Diabetes - Simple >=12 Yrs],0,1
2,MALLAM,52,1,E11.65 [Type 2 diabetes mellitus with hypergly...,E11.65 [Type 2 diabetes mellitus with hypergly...,0,0
3,awutu breku,44,1,E08.40 [Diabetes mellitus due to underlying co...,"L30.3 [Infective dermatitis] , N34.1 [Nonspeci...",0,1
4,BUBIASHIE-BEHIND ACADEMY,54,1,E11.40 [Type 2 diabetes mellitus with diabetic...,E11.40 [Type 2 diabetes mellitus with diabetic...,0,1

In [43]:

new_df.head()
# new_df.info()

,Address (Locality),Age,Sex,Principal Diagnosis (New Case),Additional Diagnosis (New Case),Pregnant Patient,NHIA Patient
0,MADINA-NEW RD,67,1,E08.40 [Diabetes mellitus due to underlying co...,"R73.9 [Hyperglycaemia, unspecified]",0,1
1,"GBAWE , TELECOM",67,1,MEDI02A [Diabetes - Simple >=12 Yrs],MEDI02A [Diabetes - Simple >=12 Yrs],0,1
2,MALLAM,52,1,E11.65 [Type 2 diabetes mellitus with hypergly...,E11.65 [Type 2 diabetes mellitus with hypergly...,0,0
3,awutu breku,44,1,E08.40 [Diabetes mellitus due to underlying co...,"L30.3 [Infective dermatitis] , N34.1 [Nonspeci...",0,1
4,BUBIASHIE-BEHIND ACADEMY,54,1,E11.40 [Type 2 diabetes mellitus with diabetic...,E11.40 [Type 2 diabetes mellitus with diabetic...,0,1

In [48]:
# s = 

# #encoding the categorical data using ordinal encoding
# from sklearn.preprocessing import OrdinalEncoder

# # Initialize the OrdinalEncoder
# encoder = OrdinalEncoder()

new_df['Principal Diagnosis (New Case)'].nunique()

121