Exploring The Dataset Collected, for our Epidemic Analysing and Monitoring System for Malaria and Diabetes

In [1]:
import pandas as pd
diabetes_df = pd.read_csv('../artifacts/csv/health_data_eams_diabetes.csv')
malaria_df = pd.read_csv('../artifacts/csv/health_data_eams_malaria.csv')

#new dfs
new_diabetes_df = diabetes_df.drop(columns=["Sr.No.", "Provisional Diagnosis", "Type Of Test(s) Requested", "Test Result(s)", "Principal Diagnosis (Old Case)", "Principal Diagnosis (Recurring Case)", "Additional Diagnosis (Old Case)", "Additional Diagnosis (Recurring Case)"])
new_malaria_df = malaria_df.drop(columns=["Sr.No.", "Provisional Diagnosis", "Type Of Test(s) Requested", "Test Result(s)", "Principal Diagnosis (Old Case)", "Principal Diagnosis (Recurring Case)", "Additional Diagnosis (Old Case)", "Additional Diagnosis (Recurring Case)"])

To create the time series, i'd time stamp the data with the months in which they were collected

In [3]:
#time stampping the data

new_malaria_df['Month'] = ''
new_diabetes_df['Month'] = ''

#diabetes time stamp
new_diabetes_df.loc[0:170, 'Month'] = '2022-03'
new_diabetes_df.loc[170:278, 'Month'] = '2022-06'
new_diabetes_df.loc[278:380, 'Month'] = '2022-09'
new_diabetes_df.loc[380:513, 'Month'] = '2022-10'
new_diabetes_df.loc[513:573, 'Month'] = '2023-03'
new_diabetes_df.loc[573:621, 'Month'] = '2023-06'
new_diabetes_df.loc[621:673, 'Month'] = '2023-09'
new_diabetes_df.loc[673:740, 'Month'] = '2023-10'
new_diabetes_df.loc[740:794, 'Month'] = '2024-03'
new_diabetes_df.loc[794:836, 'Month'] = '2024-06'
new_diabetes_df.loc[836:886, 'Month'] = '2024-09'
new_diabetes_df.loc[886:926, 'Month'] = '2024-10'


# malaria time stamp
new_malaria_df.loc[0:113, 'Month'] = '2022-03'
new_malaria_df.loc[113:430, 'Month'] = '2022-06'
new_malaria_df.loc[430:563, 'Month'] = '2022-09'
new_malaria_df.loc[563:683, 'Month'] = '2022-10'
new_malaria_df.loc[683:810, 'Month'] = '2022-03'
new_malaria_df.loc[810:992, 'Month'] = '2023-06'
new_malaria_df.loc[992:1150, 'Month'] = '2023-09'
new_malaria_df.loc[1150:1303, 'Month'] = '2023-10'
new_malaria_df.loc[1303:1351, 'Month'] = '2024-03'
new_malaria_df.loc[1351:1446, 'Month'] = '2024-06'
new_malaria_df.loc[1446:1503, 'Month'] = '2024-09'
new_malaria_df.loc[1503:1578, 'Month'] = '2024-10'

In [6]:
#flll NaN in additional diagnosis with the principal diagnosis
# def fill_na_with_principal(df):
#     df.fillna({'Additional Diagnosis (New Case)': df['Principal Diagnosis (New Case)']}, inplace=True)
#     #convert age to integers
#     df['Age'] = df['Age'].str.replace(' Year(s)', '').astype(int)
#     return df

def fill_na_with_principal(df):
    df.fillna({'Additional Diagnosis (New Case)': df['Principal Diagnosis (New Case)']}, inplace=True)
    
    # Convert age to integers - handle both years and months
    def convert_age_to_years(age_str):
        if pd.isna(age_str):
            return 0
        age_str = str(age_str).strip()
        if 'Month(s)' in age_str:
            months = int(age_str.replace(' Month(s)', ''))
            return round(months / 12, 1)  # Convert months to years
        elif 'Year(s)' in age_str:
            return int(age_str.replace(' Year(s)', ''))
        else:
            try:
                return int(age_str)
            except:
                return 0
    
    df['Age'] = df['Age'].apply(convert_age_to_years)
    return df

# convert binary data to integers
def convert_binary_to_integers(df):
    df.fillna({'Sex': df['Sex'].mode()[0]}, inplace=True)
    df['Sex'] = df['Sex'].str.lower().map({'male': 0, 'female': 1}).astype(int)
    df['Pregnant Patient'] = df['Pregnant Patient'].map({'Yes': 1, 'No': 0}).astype(int)
    df['NHIA Patient'] = df['NHIA Patient'].map({'Yes': 1, 'No': 0}).astype(int)
    return df

In [7]:
new_malaria_df = fill_na_with_principal(new_malaria_df)
new_malaria_df = convert_binary_to_integers(new_malaria_df)
new_malaria_df.head()

new_diabetes_df = fill_na_with_principal(new_diabetes_df)
new_diabetes_df = convert_binary_to_integers(new_diabetes_df)
new_diabetes_df.head()

,Address (Locality),Age,Sex,Principal Diagnosis (New Case),Additional Diagnosis (New Case),Pregnant Patient,NHIA Patient,Month
0,MADINA-NEW RD,67,1,E08.40 [Diabetes mellitus due to underlying co...,"R73.9 [Hyperglycaemia, unspecified]",0,1,2022-03
1,"GBAWE , TELECOM",67,1,MEDI02A [Diabetes - Simple >=12 Yrs],MEDI02A [Diabetes - Simple >=12 Yrs],0,1,2022-03
2,MALLAM,52,1,E11.65 [Type 2 diabetes mellitus with hypergly...,E11.65 [Type 2 diabetes mellitus with hypergly...,0,0,2022-03
3,awutu breku,44,1,E08.40 [Diabetes mellitus due to underlying co...,"L30.3 [Infective dermatitis] , N34.1 [Nonspeci...",0,1,2022-03
4,BUBIASHIE-BEHIND ACADEMY,54,1,E11.40 [Type 2 diabetes mellitus with diabetic...,E11.40 [Type 2 diabetes mellitus with diabetic...,0,1,2022-03

In [8]:
new_malaria_df.head()

,Address (Locality),Age,Sex,Principal Diagnosis (New Case),Additional Diagnosis (New Case),Pregnant Patient,NHIA Patient,Month
0,kwashieman,17,1,"B50.9 [Plasmodium falciparum malaria, unspecif...","B50.9 [Plasmodium falciparum malaria, unspecif...",0,1,2022-03
1,UPPER-WEIJA,3,0,"B50.9 [Plasmodium falciparum malaria, unspecif...","B50.9 [Plasmodium falciparum malaria, unspecif...",0,0,2022-03
2,KASOA-AKWELEY,18,0,"B50.9 [Plasmodium falciparum malaria, unspecif...","B50.9 [Plasmodium falciparum malaria, unspecif...",0,0,2022-03
3,OFANKOR\nAMASAMAN,9,0,"B50.9 [Plasmodium falciparum malaria, unspecif...","B50.9 [Plasmodium falciparum malaria, unspecif...",0,1,2022-03
4,KWASIEMAN,33,1,"B50.9 [Plasmodium falciparum malaria, unspecif...",N34.1 [Nonspecific urethritis],0,1,2022-03

In [9]:
new_diabetes_df.head()

,Address (Locality),Age,Sex,Principal Diagnosis (New Case),Additional Diagnosis (New Case),Pregnant Patient,NHIA Patient,Month
0,MADINA-NEW RD,67,1,E08.40 [Diabetes mellitus due to underlying co...,"R73.9 [Hyperglycaemia, unspecified]",0,1,2022-03
1,"GBAWE , TELECOM",67,1,MEDI02A [Diabetes - Simple >=12 Yrs],MEDI02A [Diabetes - Simple >=12 Yrs],0,1,2022-03
2,MALLAM,52,1,E11.65 [Type 2 diabetes mellitus with hypergly...,E11.65 [Type 2 diabetes mellitus with hypergly...,0,0,2022-03
3,awutu breku,44,1,E08.40 [Diabetes mellitus due to underlying co...,"L30.3 [Infective dermatitis] , N34.1 [Nonspeci...",0,1,2022-03
4,BUBIASHIE-BEHIND ACADEMY,54,1,E11.40 [Type 2 diabetes mellitus with diabetic...,E11.40 [Type 2 diabetes mellitus with diabetic...,0,1,2022-03

In [11]:
# save the time stammped csv
new_diabetes_df.to_csv('../artifacts/time_series/health_data_eams_diabetes_time_stamped.csv', index=False)
new_malaria_df.to_csv('../artifacts/time_series/health_data_eams_malaria_time_stamped.csv', index=False)

Get google trends data in relation to the one i got from weija hospital

In [2]:
# --- Google Trends Fetch with Delay and Error Handling ---
import pandas as pd
from pytrends.request import TrendReq
import time
import os

months = [
    '2022-03', '2022-06', '2022-09', '2022-10',
    '2023-03', '2023-06', '2023-09', '2023-10',
    '2024-03', '2024-06', '2024-09', '2024-10'
]

pytrends = TrendReq(hl='en-US', tz=0)
kw_list = ['diabetes', 'malaria']

results = []
progress_file = '../artifacts/time_series/google_trends_time_series.csv'

# Load progress if exists
if os.path.exists(progress_file):
    results = pd.read_csv(progress_file).to_dict('records')
    done_months = set(r['Month'] for r in results)
else:
    done_months = set()

for month in months:
    if month in done_months:
        print(f"Skipping {month}, already fetched.")
        continue
    start = f"{month}-01"
    end = pd.to_datetime(start) + pd.offsets.MonthEnd(0)
    timeframe = f"{start} {end.strftime('%Y-%m-%d')}"
    try:
        pytrends.build_payload(kw_list, timeframe=timeframe, geo='')
        df = pytrends.interest_over_time()
        if not df.empty:
            diabetes_trend = df['diabetes'].mean()
            malaria_trend = df['malaria'].mean()
        else:
            diabetes_trend = malaria_trend = None
        results.append({'Month': month, 'diabetes_trend': diabetes_trend, 'malaria_trend': malaria_trend})
        # Save progress after each fetch
        pd.DataFrame(results).to_csv(progress_file, index=False)
        print(f"Fetched and saved {month}")
    except Exception as e:
        print(f"Error for {month}: {e}")
    time.sleep(60)  # Wait 60 seconds between requests

trends_df = pd.DataFrame(results)
print(trends_df)

Skipping 2022-03, already fetched.
Skipping 2022-06, already fetched.
Skipping 2022-09, already fetched.
Skipping 2022-10, already fetched.
Skipping 2023-03, already fetched.
Skipping 2023-06, already fetched.
Skipping 2023-09, already fetched.
Skipping 2023-10, already fetched.
Fetched and saved 2024-03
Skipping 2024-06, already fetched.
Skipping 2024-09, already fetched.
Skipping 2024-10, already fetched.
      Month  diabetes_trend  malaria_trend
0   2022-03       90.870968      11.741935
1   2022-06       84.900000      11.000000
2   2022-09       89.200000      13.066667
3   2022-10       88.870968      12.709677
4   2023-03       90.129032      11.258065
5   2023-06       87.866667      13.633333
6   2023-09       87.800000      13.133333
7   2023-10       86.612903      12.870968
8   2024-06       88.766667      11.300000
9   2024-09       89.966667      12.566667
10  2024-10       87.548387      11.612903
11  2024-03       85.258065      10.677419